platform :ios, '10.0'
use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = "true" ## This disabled the Sending Stats when running Pod install in terminal

target 'PopupDialog_Example' do

  pod 'PopupDialog', :path => '../'
  pod 'SwiftLint', '~> 0.35'
  pod 'QMUIKit/QMUICore', '4.2.0'
  pod 'RxSwiftExt', '5.2.0'
  pod 'RxDataSources', '4.0.1'
  pod 'RxViewController', '1.0.0'
  pod 'NSObject+Rx', '5.1.0'
  pod 'Moya/RxSwift', '14.0.0'
  pod 'ObjectMapper', '4.2.0'
  pod 'ReactorKit', '2.1.0'
  pod 'URLNavigator', '2.3.0'
  pod 'BonMot', '5.5.1'
  pod 'SwifterSwift', '5.2.0'
  pod 'FCUUID', '1.3.1'
  pod 'Kingfisher', '5.14.0'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'ESPullToRefresh', '2.9.3'
  pod 'RxOptional', '4.0.0'
  pod 'RxGesture', '3.0.0'
  pod 'RxTheme', '4.1.0'
  pod 'DefaultsKit', '0.2.0'
  pod 'Cache', '5.3.0'
  pod 'BlueSocket', '1.0.52'
  # pod 'SwiftEntryKit-JX', '1.2.3'
  pod 'SwiftEntryKit', '1.2.6'
  pod 'IQKeyboardManagerSwift', '6.5.5'
  pod 'ReusableKit/RxSwift', '3.0.0'
  pod 'Toast-Swift', '5.0.1'
  pod 'R.swift', '5.2.2'
  pod 'SwiftLint', '0.39.2'
  pod 'MarqueeLabel', '4.0.2'
  # pod 'MLeaksFinder', '1.0.0'
  pod 'lottie-ios', '3.1.8'
  pod 'Umbrella/Core', '0.9.0'
  # pod 'FLEX', '3.0.0'
  pod 'GT3Captcha-iOS', '0.14.0'
  pod 'Parchment', '2.4.0'
  pod 'SnapKit', '5.0.1'
  pod 'UMCCommon', '7.1.1'
  pod 'BetterSegmentedControl', '2.0.1'
  pod 'LGButton', '1.1.6'
  pod 'Weak', '1.0.0'
  pod 'KissXML', '5.3.1'
  
  target 'PopupDialog_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.3.1'
    pod 'iOSSnapshotTestCase', '~> 6.0.2'

  end
end
