version: 2
jobs:
  build-and-test:
    macos:
      xcode: "13.2.1"
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild -project Parchment.xcodeproj -scheme "Parchment" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2' test
      - run:
          name: Run UI Tests
          command: xcodebuild -project Parchment.xcodeproj -scheme "ParchmentUITests" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2' test
      
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
