source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'MySwiftEntryKit' do
	pod 'SWFrame', :path => '../../../../SWFrame'
	pod 'SwiftEntryKit', '1.2.3'
end
