osx_image: xcode10
language: objective-c

before_script:
    - cd Example
    - pod install

script:
    - xcodebuild clean build -sdk iphonesimulator12.0 -workspace LGButton.xcworkspace -scheme LGButton-Example CODE_SIGNING_REQUIRED=NO

branches:
  only:
  - master
  - develop
