language: objective-c
osx_image: xcode7.3
cache:
  directories:
  - Carthage
install:
- bin/bootstrap-if-needed
script:
- xctool -project Specht.xcodeproj -scheme "Specht" -sdk macosx10.11 -arch
  x86_64 build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO